# 开发环境配置
spring:
  thymeleaf:
    cache: false
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: root
          password: Yapi1234
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://rm-2zep3xy7yb8h7h3hzyo.mysql.rds.aliyuncs.com:3306/yapi
